module.exports = {
  "ALIVE_IMG": "https://ibb.co/rpdMtLG",
  "PREFIX": "#",
  "AUTO_READ_STATUS": false,
  "MODE": "public",
  "BOT_NUMBER": "923127233098",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": true,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "Shahzaib",
  "NEWS_JID": "https://whatsapp.com/channel/0029VaCfilvC6ZvfnZltPh41",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false
};
